import "package:flutter/material.dart";

class MaterialTheme {

  const MaterialTheme();

  static ColorScheme lightScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff6b4f8c),
      surfaceTint: Color(0xff6d528f),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff8468a7),
      onPrimaryContainer: Color(0xfffffbff),
      secondary: Color(0xff3f3150),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff564868),
      onSecondaryContainer: Color(0xffcbb9de),
      tertiary: Color(0xff000000),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff1c1b1b),
      onTertiaryContainer: Color(0xff858383),
      error: Color(0xffba1a1a),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffffdad6),
      onErrorContainer: Color(0xff93000a),
      surface: Color(0xfffdf8f8),
      onSurface: Color(0xff1c1b1b),
      onSurfaceVariant: Color(0xff4a454f),
      outline: Color(0xff7b7580),
      outlineVariant: Color(0xffccc4d0),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff313030),
      inversePrimary: Color(0xffd9b9fe),
      primaryFixed: Color(0xffeedbff),
      onPrimaryFixed: Color(0xff270b47),
      primaryFixedDim: Color(0xffd9b9fe),
      onPrimaryFixedVariant: Color(0xff553a75),
      secondaryFixed: Color(0xffeddcff),
      onSecondaryFixed: Color(0xff221632),
      secondaryFixedDim: Color(0xffd2bfe5),
      onSecondaryFixedVariant: Color(0xff4e4160),
      tertiaryFixed: Color(0xffe5e2e1),
      onTertiaryFixed: Color(0xff1c1b1b),
      tertiaryFixedDim: Color(0xffc8c6c5),
      onTertiaryFixedVariant: Color(0xff474746),
      surfaceDim: Color(0xffddd9d8),
      surfaceBright: Color(0xfffdf8f8),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff7f3f2),
      surfaceContainer: Color(0xfff1edec),
      surfaceContainerHigh: Color(0xffebe7e6),
      surfaceContainerHighest: Color(0xffe5e2e1),
    );
  }

  static ColorScheme darkScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffd9b9fe),
      surfaceTint: Color(0xffd9b9fe),
      onPrimary: Color(0xff3d235d),
      primaryContainer: Color(0xffa184c5),
      onPrimaryContainer: Color(0xff2a0f4a),
      secondary: Color(0xffd2bfe5),
      onSecondary: Color(0xff372b49),
      secondaryContainer: Color(0xff564868),
      onSecondaryContainer: Color(0xffcbb9de),
      tertiary: Color(0xffc8c6c5),
      onTertiary: Color(0xff313030),
      tertiaryContainer: Color(0xff161616),
      onTertiaryContainer: Color(0xff817f7f),
      error: Color(0xffffb4ab),
      onError: Color(0xff690005),
      errorContainer: Color(0xff93000a),
      onErrorContainer: Color(0xffffdad6),
      surface: Color(0xff141313),
      onSurface: Color(0xffe5e2e1),
      onSurfaceVariant: Color(0xffccc4d0),
      outline: Color(0xff958e99),
      outlineVariant: Color(0xff4a454f),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe5e2e1),
      inversePrimary: Color(0xff6d528f),
      primaryFixed: Color(0xffeedbff),
      onPrimaryFixed: Color(0xff270b47),
      primaryFixedDim: Color(0xffd9b9fe),
      onPrimaryFixedVariant: Color(0xff553a75),
      secondaryFixed: Color(0xffeddcff),
      onSecondaryFixed: Color(0xff221632),
      secondaryFixedDim: Color(0xffd2bfe5),
      onSecondaryFixedVariant: Color(0xff4e4160),
      tertiaryFixed: Color(0xffe5e2e1),
      onTertiaryFixed: Color(0xff1c1b1b),
      tertiaryFixedDim: Color(0xffc8c6c5),
      onTertiaryFixedVariant: Color(0xff474746),
      surfaceDim: Color(0xff141313),
      surfaceBright: Color(0xff3a3939),
      surfaceContainerLowest: Color(0xff0e0e0e),
      surfaceContainerLow: Color(0xff1c1b1b),
      surfaceContainer: Color(0xff201f1f),
      surfaceContainerHigh: Color(0xff2b2a2a),
      surfaceContainerHighest: Color(0xff353434),
    );
  }
}
